### ISSUE TITLE
mermaid integration

### ISSUE THREAD

**Issue by pubmania** [Seao/grav-plugin-diagrams#1]
Thanks for this useful plugin. Would it be possible to integrate [mermaid](https://github.com/knsv/mermaid) to this plugin?

With my limited understanding of code, I wonder if it is as simple as adding the [mermaid.js](https://github.com/knsv/mermaid/tree/master/dist) into the js directory and then including the line `$this->grav['assets']->addJs('plugin://diagrams/js/mermaid.js');` in diagrams.php at line 132?

**Comment by Seao** [comment]
Hi  @pubmania ,

Thanks for your feedback!

I added mermaid support to the plugin (https://github.com/Seao/grav-plugin-diagrams/commit/c0dd8ee42410c00d02ef27da5fe48bdbdbaf21d3). This modification is currently not deployed on GPM, which mean you have to [install the plugin manually](https://github.com/Seao/grav-plugin-diagrams/blob/master/README.md#manual-installation).

Usage instructions are available on the README. Could you please try it, and if everything is working for you I will deploy it for everyone and close this issue 😉

**Comment by pubmania** [comment]
Hi @Seao ,

Thanks for the quick response. It is indeed working. I checked with sequence diagram and gantt chart and both work wonderfully well.

It can be deployed to GPM indeed. Although I wonder if it will be possible to do one more addition to the feature for Gantt....How it goes is like this:

For Gantt charts, mermaid uses d3 js library and the default period is in weeks. Now the [markdown plus tool](https://github.com/tylingsoft/markdown-plus) allows for Gantt X-axis formatting ... if you look at their demo [here](http://mdp.tylingsoft.com/#preferences-modal).

Is it something that can be implemented under settings or even on per post basis.

**Comment by Seao** [comment]
It's now possible to modify the axis of gantt diagram in the plugin's parameters (https://github.com/Seao/grav-plugin-diagrams/commit/1f7976b0192aa3443eba6e90143998ad2d44565f). I will push a new version on GPM, it will be available soon. Of course manually install is still possible :)

**Comment by pubmania** [comment]
Fabulous...You are absolute star. Thanks :+1:
