### ISSUE TITLE
add graphviz js in this plugin

### ISSUE THREAD

**Issue by Maclaon** [Seao/grav-plugin-diagrams#10]
hi, can u add [graphviz](https://www.graphviz.org/) in this plugin, it will powerful!

**Comment by Maclaon** [comment]
togethe with [planuml](http://en.plantuml.com/)

**Comment by Seao** [comment]
Hi @Maclaon, I agree with you, however I no longer have enough time to devote to this plugin, so there will be no additional features developed. Sorry about that, but feel free to send [pull request](https://github.com/Seao/grav-plugin-diagrams/pulls) if you are interested about contributing 👍
