### ISSUE TITLE
add the ability to save/export the diagram as svg

### ISSUE THREAD

**Issue by jprobichaud** [Seao/grav-plugin-diagrams#11]
A nice feature you can see on https://bramp.github.io/js-sequence-diagrams/ is the ability to export the diagrams as an svg.  This is quite useful when one wants to share diagrams as part of a documentation effort

**Comment by Seao** [comment]
Indeed it would be a great feature, however I no longer have enough time to work on this plugin, so there will be no additional features developed. Sorry about that, but feel free to send [pull request](https://github.com/Seao/grav-plugin-diagrams/pulls) if you are interested about contributing!
