### ISSUE TITLE
working link syntax

### ISSUE THREAD

**Issue by neo4a** [Seao/grav-plugin-diagrams#12]
Working with Grav 1.5.1 and latest plugin source installed from Github.

I'm not able to provide a working link syntax. Following example provides a diagram but link target is wrong:

[mermaid]
graph TD

st{<a href=''http://google.com''>Google</a> test}

[/mermaid]

Is inserting a link somehow limited?

**Comment by Seao** [comment]
Hi, sorry for the *very* late response. Maybe someone will go through this issue, who knows? It seems that your syntax is not good, something like that will work better:

```
[mermaid]
graph TD; 
  ST{Google Test}
  click ST "http://google.com" "Link"
[/mermaid]
```
