### ISSUE TITLE
Diagrams won't render

### ISSUE THREAD

**Issue by berthelemy** [Seao/grav-plugin-diagrams#2]
Hi there,
I'm using this plugin with the Learn2 theme (via the Skeleton: Learn2 with Git Sync Site).
When I put in the sample markdown, for either a flowchart or a sequence diagram, the instructions are not being rendered as a diagram. They just appear as text.

For example:

[sequence]
A->B:Hi C for me !
B-->A:With pleasure
B->C:A says hello
[/sequence]

is seen in the HTML as:

<div class="diagram" style="text-align:center">
A->B:Hi C for me !
B-->A:With pleasure
B->C:A says hello
</div>

I was expecting it to convert to svg.

I'm using Chrome on Ubuntu.

[EDIT]
I've noticed that the console is stating:
(index):21 Uncaught ReferenceError: $ is not defined
It appears to be referring to this line:
$(document).ready(function() {
So, is there a dependency on JQuery that isn't being met?
[/EDIT]

Thanks,

Mark

**Comment by berthelemy** [comment]
Update. When I switch off the Javascript pipeline in the site config, the diagrams render OK.

**Comment by Seao** [comment]
Hey @berthelemy ! Sorry, I didn't notice you opened this issue one month ago. I'm glad to see you solved it 👍 Thanks for using my plugin !
