### ISSUE TITLE
Upgrade problems

### ISSUE THREAD

**Issue by molnar-elod-nx** [Seao/grav-plugin-diagrams#3]
Hello!

With the 1.0.0 version everything works like a charm, but then I saw .. and wanted to use mermaid charts..
If I upgrade to the 1.0.1 version it breaks the whole site :-( even $ remains undefined.
The built `js` file has a syntax error. Where to begin debugging in this case?

**Comment by Seao** [comment]
Hi @molnarelod, I'm sorry I have not seen the notification for this problem ... I hope you have found a solution ! It is strange that the JS file built is problematic, I have never encountered this case. I just submitted a new version that fixes some stuff, if everything is not working as expected with it please reopen this issue, I would find a solution !
