### ISSUE TITLE
Not working after update from 1.0.1 to 1.0.3

### ISSUE THREAD

**Issue by jorgemfm** [Seao/grav-plugin-diagrams#5]
Hi,

Updated from 1.0.1 to 1.0.3 and the diagrams are no longer working

Grav version: 1.3.10

**Comment by Seao** [comment]
Hi @jorgemfm,

There are only two CSS lines modified in the new version 1.0.3, it's strange that diagrams doesn't work anymore. Which diagrams are involved : sequence, flow or mermaid ? Do you use a specific theme on your site ?

You can downgrade the plugin version by installing a functional version from the [release](https://github.com/Seao/grav-plugin-diagrams/releases) page while I solve this error.

**Comment by jorgemfm** [comment]
It happens on all diagrams, but I noticed somethin else, with the plugin enabled the copy icon no longer appears when I surround the text with "`"

Diagram plugin disabled: https://imgur.com/a/e4I0X

Diagram plugin enabled: https://imgur.com/a/FQnHH

I Use the same theme as the https://learn.getgrav.org site


EDIT: 

> There are only two CSS lines modified in the new version 1.0.3

I Updated from 1.0.1 to 1.0.3.  The css file was added in 1.0.2

**Comment by Seao** [comment]
I installed locally the theme learn2, which is the one used to create the official grav documentation website. However I hadn't be able to reproduce your issue, the plugin version 1.0.3 is working as expected and all the diagrams are created correctly. I tried with all the supported page templates : default, docs, chapter and error view.

Please could you try to reinstall the plugin using GPM, as explained in the documentation ? Also could you send the console logs ? There are probably some errors thrown if something unexpected is happening.

**Comment by jorgemfm** [comment]
The one on the https://learn.getgrav.org is a little bit diferent from the learn2.

Back then i think I've downloaded the Learn Grav Documentation from git anda applied the theme on my site. That's probably the cause.

I tried re-installing but I get the same problem, theres no error on the console.

I think you can close this since the problem is possibily the usage of this different learn theme, I will probably change to learn2 from the theme repo.

Thank you.
